package example.createorder;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Credentials implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "email")
   private java.lang.String email;
   @org.kie.api.definition.type.Label(value = "password")
   private java.lang.String password;

   public Credentials()
   {
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getPassword()
   {
      return this.password;
   }

   public void setPassword(java.lang.String password)
   {
      this.password = password;
   }

   public Credentials(java.lang.String email, java.lang.String password)
   {
      this.email = email;
      this.password = password;
   }

}