package example.airmord;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Complaint implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "COMPLAINT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "COMPLAINT_ID_GENERATOR", sequenceName = "COMPLAINT_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Email")
   private java.lang.String email;

   @org.kie.api.definition.type.Label("Text")
   private java.lang.String text;

   @org.kie.api.definition.type.Label(value = "Is complaint clear?")
   private java.lang.Boolean clear;

   @org.kie.api.definition.type.Label(value = "Is complaint valid?")
   private java.lang.Boolean valid;

   @org.kie.api.definition.type.Label(value = "Is complaint based on technical issue?")
   private java.lang.Boolean technicalIssue;

   public Complaint()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getText()
   {
      return this.text;
   }

   public void setText(java.lang.String text)
   {
      this.text = text;
   }

   public java.lang.Boolean getClear()
   {
      return this.clear;
   }

   public void setClear(java.lang.Boolean clear)
   {
      this.clear = clear;
   }

   public java.lang.Boolean getValid()
   {
      return this.valid;
   }

   public void setValid(java.lang.Boolean valid)
   {
      this.valid = valid;
   }

   public java.lang.Boolean getTechnicalIssue()
   {
      return this.technicalIssue;
   }

   public void setTechnicalIssue(java.lang.Boolean technicalIssue)
   {
      this.technicalIssue = technicalIssue;
   }

   public Complaint(java.lang.Long id, java.lang.String email,
         java.lang.String text, java.lang.Boolean clear,
         java.lang.Boolean valid, java.lang.Boolean technicalIssue)
   {
      this.id = id;
      this.email = email;
      this.text = text;
      this.clear = clear;
      this.valid = valid;
      this.technicalIssue = technicalIssue;
   }

}