package example.airmord;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Complaint implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "COMPLAINT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "COMPLAINT_ID_GENERATOR", sequenceName = "COMPLAINT_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Email")
   private java.lang.String email;

   @org.kie.api.definition.type.Label("Text")
   private java.lang.String text;

   @org.kie.api.definition.type.Label("Additional information request text")
   private java.lang.String comment;

   public Complaint()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getText()
   {
      return this.text;
   }

   public void setText(java.lang.String text)
   {
      this.text = text;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public Complaint(java.lang.Long id, java.lang.String email,
         java.lang.String text, java.lang.String comment)
   {
      this.id = id;
      this.email = email;
      this.text = text;
      this.comment = comment;
   }

}