package example.airmord;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Ticket implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TICKET_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "TICKET_ID_GENERATOR", sequenceName = "TICKET_ID_SEQ")
   private java.lang.Long id;

   private java.lang.String text;

   private java.lang.String complaint;

   public Ticket()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getText()
   {
      return this.text;
   }

   public void setText(java.lang.String text)
   {
      this.text = text;
   }

   public java.lang.String getComplaint()
   {
      return this.complaint;
   }

   public void setComplaint(java.lang.String complaint)
   {
      this.complaint = complaint;
   }

   public Ticket(java.lang.Long id, java.lang.String text,
         java.lang.String complaint)
   {
      this.id = id;
      this.text = text;
      this.complaint = complaint;
   }

}